/**
 * AKEYLESS Vault API
 * RESTFull API for interacting with AKEYLESS Vault API
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: refael@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ErrorReplyObj from './com.akeyless.api_gateway.swagger.model/ErrorReplyObj';
import ReplyObj from './com.akeyless.api_gateway.swagger.model/ReplyObj';
import DefaultApi from './com.akeyless.api_gateway.swagger.api/DefaultApi';


/**
* RESTFull_API_for_interacting_with_AKEYLESS_Vault_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AkeylessVaultApi = require('com.akeyless.api_gateway.swagger/index'); // See note below*.
* var xxxSvc = new AkeylessVaultApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AkeylessVaultApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['com.akeyless.api_gateway.swagger/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AkeylessVaultApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AkeylessVaultApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module com.akeyless.api_gateway.swagger/index
* @version 0.1.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:com.akeyless.api_gateway.swagger/ApiClient}
     */
    ApiClient,

    /**
     * The ErrorReplyObj model constructor.
     * @property {module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ErrorReplyObj}
     */
    ErrorReplyObj,

    /**
     * The ReplyObj model constructor.
     * @property {module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ReplyObj}
     */
    ReplyObj,

    /**
    * The DefaultApi service constructor.
    * @property {module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.api/DefaultApi}
    */
    DefaultApi
};
