/*
 * AKEYLESS Vault API
 * RESTFull API for interacting with AKEYLESS Vault API
 *
 * OpenAPI spec version: 0.1.1
 * Contact: refael@akeyless.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.akeyless.api_gateway.swagger/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AkeylessVaultApi) {
      root.AkeylessVaultApi = {};
    }
    root.AkeylessVaultApi.ErrorReplyObj = factory(root.AkeylessVaultApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ErrorReplyObj model module.
   * @module com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ErrorReplyObj
   * @version 0.1.1
   */

  /**
   * Constructs a new <code>ErrorReplyObj</code>.
   * Response with error description
   * @alias module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ErrorReplyObj
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ErrorReplyObj</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ErrorReplyObj} obj Optional instance to populate.
   * @return {module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ErrorReplyObj} The populated <code>ErrorReplyObj</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }

  /**
   * Internal error code
   * @member {String} error
   */
  exports.prototype.error = undefined;

  /**
   * Error message
   * @member {String} message
   */
  exports.prototype.message = undefined;

  return exports;

}));
