/*
 * AKEYLESS Vault API
 * RESTFull API for interacting with AKEYLESS Vault API
 *
 * OpenAPI spec version: 0.1.1
 * Contact: refael@akeyless.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.akeyless.api_gateway.swagger/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AkeylessVaultApi) {
      root.AkeylessVaultApi = {};
    }
    root.AkeylessVaultApi.ReplyObj = factory(root.AkeylessVaultApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ReplyObj model module.
   * @module com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ReplyObj
   * @version 0.1.1
   */

  /**
   * Constructs a new <code>ReplyObj</code>.
   * Base response
   * @alias module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ReplyObj
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ReplyObj</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ReplyObj} obj Optional instance to populate.
   * @return {module:com.akeyless.api_gateway.swagger/com.akeyless.api_gateway.swagger.model/ReplyObj} The populated <code>ReplyObj</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('command'))
        obj.command = ApiClient.convertToType(data['command'], 'String');
      if (data.hasOwnProperty('response'))
        obj.response = ApiClient.convertToType(data['response'], Object);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} command
   */
  exports.prototype.command = undefined;

  /**
   * @member {Object} response
   */
  exports.prototype.response = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} token
   */
  exports.prototype.token = undefined;

  return exports;

}));
